INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_PSW_BACKUP_CODE', 'Inserisci la password e un codice di backup  generato precedentemente # Inserisci un codice di backup per completare l\'autenticazione');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_PSW_SIX_APP', 'Inserisci la password e il codice di sei cifre che riceverai sull\'authenticator # Inserisci il codice di 6 cifre che ti è stato mandato sull\'authenticator');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_PSW_SIX_EMAIL', 'Inserisci la password e il codice di sei cifre che riceverai via email # Inserisci il codice di 6 cifre che ti è stato mandato via email');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_PSW_SI_NO_APP', 'Inserisci la password, poi autorizza l\'accesso dall\'authenticator # Apri l\'authenticator e segui le istruzioni per completare l\'autenticazione');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_SIX_APP', 'Inserisci il codice di sei cifre che riceverai sull\'authenticator # Apri l\'authenticator e inserisci il codice di sei cifre che ti è stato mandato');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_SI_NO_APP', 'Autorizza l\'accesso dall\'authenticator # Apri l\'authenticator e segui le istruzioni per completare l\'autenticazione');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('QR_CODE', 'Inquadra il QrCode con l\'authenticator per effettuare l\'accesso');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_SIX_TELEGRAM', 'Inserisci il codice di sei cifre che riceverai su Telegram # Apri Telegram e inserisci il codice di sei cifre che ti è stato mandato');
INSERT INTO `au_t_metodi_login` (`idTipoMetodoLogin`, `descrizione`) VALUES('EMAIL_SIX_TOTP', 'Inserisci il codice di sei cifre che troverai sull\'authenticator TOTP # Apri l\'authenticator TOTP e inserisci il codice di sei cifre mostrato a video');
--
--
--
INSERT INTO `au_t_metodi_rec_psw` (`idTipoMetodoRecPsw`, `descrizione`) VALUES('REC_PSW_EMAIL_SIX_APP', 'Ricevi il codice di verifica sull\'authenticator # Inserisci il codice di verifica e la nuova password');
INSERT INTO `au_t_metodi_rec_psw` (`idTipoMetodoRecPsw`, `descrizione`) VALUES('REC_PSW_EMAIL_SIX_EMAIL', 'Ricevi il codice di verifica tramite email # Inserisci il codice di verifica ricevuto via email e la nuova password');
INSERT INTO `au_t_metodi_rec_psw` (`idTipoMetodoRecPsw`, `descrizione`) VALUES('REC_PSW_EMAIL_SIX_TELEGRAM', 'Ricevi il codice di verifica su Telegram # Inserisci il codice di verifica e la nuova password');
--
--
--
INSERT INTO `au_t_ruoli` (`idTipoRuolo`, `descrizione`) VALUES('AMM', 'Amministratore');
INSERT INTO `au_t_ruoli` (`idTipoRuolo`, `descrizione`) VALUES('USER', 'Utente');
INSERT INTO `au_t_ruoli` (`idTipoRuolo`, `descrizione`) VALUES('SPES', 'Utente spesa');
--
--
--
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_CHIAVE_GLOBALE', 'getChiaveGlobale', 'Recupero della chiave globale OTP', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ASSOCIA_RUOLO_RISORSA', 'associaRuoloRisorsa', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ASSOCIA_RUOLO_UTENTE', 'associaRuoloUtente', 'Associa un ruolo ad un utente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ASSOCIA_RUOLO_VOCE_MENU', 'associaRuoloVoceMenu', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_AZZERA_CONTATORE_ALERT', 'azzeraContatoreAlert', 'Azzera', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_BLOCCA_INDIRIZZO_IP', 'bloccaIndirizzoIp', 'Blocca', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_BLOCCA_UTENTE', 'bloccaUtente', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_DISSOCIA_RUOLO_RISORSA', 'dissociaRuoloRisorsa', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_DISSOCIA_RUOLO_UTENTE', 'dissociaRuoloUtente', 'Rimuove un ruolo ad un utente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_DISSOCIA_RUOLO_VOCE_MENU', 'dissociaRuoloVoceMenu', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ELIMINA_NOTIFICA', 'eliminaNotifica', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ELIMINA_RISORSA', 'eliminaRisorsa', 'La risorsa se ha prefisso AMM_ non potrà essere eliminata', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ELIMINA_T_RUOLO', 'eliminaRuolo', 'Non si può eliminare il ruolo AMM', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ELIMINA_UTENTE', 'eliminaUtente', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_ELIMINA_VOCE_MENU', 'eliminaVoceMenu', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_COMBO_RUOLI', 'getComboRuoli', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_DESTINATARI_NOTIFICA', 'getDestinatariNotifica', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_LISTA_ACCESSI', 'getListaAccessi', 'boh', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_LISTA_DISPOSITIVI_FISICI', 'getListaDispositiviFisici', 'Boh', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_LISTA_DISPOSITIVI_FISICI_TELEGRAM', 'getListaDispositiviFisiciTelegram', 'getListaDispositiviFisiciTelegram', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_LISTA_NOTIFICHE', 'getListaNotifiche', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_LISTA_VOCI_MENU', 'getVociMenu', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_MENU_PER_RUOLO', 'getVociMenuPerRuolo', 'Dai lista voci menu con flag ASSOCIATO NON ASSOCIATO', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NOTIFICA', 'getNotifica', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NUMERO_ACCESSI_ATTIVI', 'getNumeroAccessiAttivi', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NUMERO_DISPOSITIVI_FISICI_ATTIVI', 'getNumeroDispositiviFisiciAttivi', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NUMERO_INDIRIZZI_IP', 'getNumeroIndirizziIp', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NUMERO_RISORSE', 'getNumeroRisorse', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NUMERO_RUOLI', 'getNumeroRuoli', 'boh', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NUMERO_UTENTI', 'getNumeroUtenti', 'boh', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_NUMERO_VOCI_MENU', 'getNumeroVociMenu', 'boh', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_RISORSA', 'getRisorsa', 'La risorsa se ha prefisso AMM_ sarà in sola lettura', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_RISORSE_PER_RUOLO', 'getRisorsePerRuolo', 'Dai lista risorse con flag ASSOCIATO NON ASSOCIATO', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_STATISTICHE_METODI', 'getStatisticheMetodi', 'Statistiche grafico homepage', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_T_RUOLO', 'getRuolo', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_UTENTE', 'getUtente', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_UTENTI_RUOLO', 'getUtentiPerRuolo', 'Dai lista utenti con flag ASSOCIATO NON ASSOCIATO', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_GET_VOCE_MENU', 'getVoceMenu', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INSERISCI_NOTIFICA', 'inserisciNotifica', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INSERISCI_RISORSA', 'inserisciRisorsa', 'La risorsa non può avere prefisso AMM_', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INSERISCI_T_RUOLO', 'inserisciRuolo', 'Non si può inserire il ruolo AMM', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INSERISCI_UTENTE', 'inserisciUtente', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INSERISCI_VOCE_MENU', 'inserisciVoceMenu', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INVIA_NOTIFICA_RUOLO', 'inviaNotificaRuolo', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INVIA_NOTIFICA_TUTTI', 'inviaNotificaTutti', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_INVIA_NOTIFICA_UTENTE', 'inviaNotificaUtente', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LISTA_INDIRIZZI_IP', 'getIndirizziIp', 'Lista indirizzi ip', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LISTA_RISORSE', 'getRisorse', 'Prova', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LISTA_T_RUOLI', 'getRuoli', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LISTA_UTENTI', 'getListaUtenti', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LOG_DEBUG', 'getLogs', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LOG_ERROR', 'getLogs', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LOG_INFO', 'getLogs', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LOG_TELEGRAM', 'getLogsTelegram', 'getLogsTelegram', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_LOG_WARN', 'getLogs', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_MODIFICA_NOTIFICA', 'modificaNotifica', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_MODIFICA_RISORSA', 'modificaRisorsa', 'La risorsa se ha prefisso AMM_ non potrà essere modificata', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_MODIFICA_T_RUOLO', 'modificaRuolo', 'Non si può modificare il ruolo AMM', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_MODIFICA_UTENTE', 'modificaUtente', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_MODIFICA_VOCE_MENU', 'modificaVoceMenu', 'Descrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_NOTIFICHE_TELEGRAM', 'getNotificheTelegram', 'getNotificheTelegram', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_NUMERO_LOGIN', 'getNumeroLogin', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_RIMUOVI_DISPOSITIVO_FISICO', 'rimuoviDispositivoFisico', 'boh', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_RIMUOVI_DISPOSITIVO_FISICO_TELEGRAM', 'rimuoviDispositivoFisicoTelegram', 'rimuoviDispositivoFisicoTelegram', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_SBLOCCA_INDIRIZZO_IP', 'sbloccaIndirizzoIp', 'Sblocca', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_SBLOCCA_UTENTE', 'sbloccaUtente', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('AMM_TERMINA_ACCESSO', 'terminaAccesso', 'BOH', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_ABILITA_TIPO_METODO_LOGIN', 'abilitaTipoMetodoLogin', 'abilitaTipoMetodoLogin', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_ABILITA_TIPO_RECUPERO_PASSWORD', 'abilitaTipoRecuperoPassword', 'abilitaTipoRecuperoPassword', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_DISABILITA_DISPOSITIVO_FISICO', 'disabilitaDispositivoFisico', 'disabilitaDispositivoFisico', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_DISABILITA_TIPO_METODO_LOGIN', 'disabilitaTipoMetodoLogin', 'disabilitaTipoMetodoLogin', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_DISABILITA_TIPO_RECUPERO_PASSWORD', 'disabilitaTipoRecuperoPassword', 'disabilitaTipoRecuperoPassword', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_ELIMINA_NOTIFICA', 'eliminaNotificaLatoUtente', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GENERA_CODICI_BACKUP', 'generaCodiciBackup', 'generaCodiciBackup', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GENERA_CHIAVE_PERSONALE_TOTP', 'generaChiavePersonaleTOTP', 'generaChiavePersonaleTOTP', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GENERA_ID_DISPOSITIVO_FISICO', 'generaIdentificativoDispositivoFisico', 'generaIdentificativoDispositivoFisico', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GENERA_ID_TELEGRAM', 'generaIdentificativoTelegram', 'generaIdentificativoTelegram', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_COMBO_VOCI_MENU', 'getComboVociMenu', 'Restituisce l\'elenco delle voci di menu per le combo', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_METODI_AUTENTICAZIONE_PER_UTENTE_LOGGATO', 'getMetodiAutenticazionePerUtenteLoggato', 'getMetodiAutenticazionePerUtenteLoggato', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_METODI_RECUPERO_PASSWORD_UTENTE_LOGGATO', 'getMetodiRecuperoPasswordPerUtenteLoggato', 'getMetodiRecuperoPasswordPerUtenteLoggato', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_NOTIFICA', 'getNotificaLatoUtente', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_NOTIFICHE', 'getNotificheLatoUtente', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_STORICO_ACCESSI', 'getStoricoAccessi', 'getStoricoAccessi', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_UTENTE_LOGGATO', 'getUtenteLoggato', 'Verifica autenticazione utente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_GET_VOCI_MENU_PER_UTENTE', 'getVociMenuPerUtente', 'Restituisce il menu utente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_INVALIDA_TOKEN', 'invalidaToken', 'invalidaTokenSpecifico', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_IS_DISPOSITIVO_ABILITATO', 'isDispositivoAbilitato', 'isDispositivoAbilitato', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_LEGGI_NOTIFICHE', 'leggiNotificheLatoUtente', 'a', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_LISTA_DISPOSITIVI_FISICI', 'getDispositiviFisici', 'getDispositiviFisici', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_LISTA_DISPOSITIVI_FISICI_TELEGRAM', 'getDispositiviFisiciTelegram', 'getDispositiviFisiciTelegram', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_VERIFICA_AUTENTICAZIONE', 'verificaAutenticazione', 'Verifica autenticazione utente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_SOTTOSCRIZIONE', 'aggiornaSottoscrizione', 'aggiornaSottoscrizione', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('USER_LISTA_UTENTI', 'getListaUtenti', '', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_MODIFICA_SPESA', 'modificaSpesa', 'Metodo per modificare una spesa', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_MODIFICA_PIETANZA', 'modificaPietanza', 'Metodo per modificare una pietanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_MODIFICA_INGREDIENTE', 'modificaIngrediente', 'Metodo per modificare un ingrediente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_MODIFICA_MENU_ALIMENTARE', 'modificaMenuAlimentare', 'Metodo per modificare un menu alimentare', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_INSERISCI_SPESA', 'inserisciSpesa', 'Metodo per inserire una spesa', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_INSERISCI_PIETANZA', 'inserisciPietanza', 'Metodo per inserire una nuova pietanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_INSERISCI_INGREDIENTE', 'inserisciIngrediente', 'Metodo per inserire un ingrediente ', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_INSERISCI_MENU_ALIMENTARE', 'inserisciMenuAlimentare', 'Metodo per inserire un nuovo menu alimentare', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_ULTIME_DATE_SOMMINISTRAZIONE_PIETANZA', 'getUltimeDateSomministrazionePietanza', 'Metodo per recuperare la lista delle somministrazioni pietanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_SEGNAPOSTI_BY_ANNO', 'getSegnapostiByAnno', 'Metodo per recuperare i luoghi visitati dato un anno', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_SEGNAPOSTI_BY_COORDINATE', 'getSegnapostiByCoordinate', 'Metodo per recuperare i segnaposti data coordinata e distanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_PIETANZA', 'getPietanza', 'Metodo per recuperare una singola pietanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_PIETANZE', 'getPietanze', 'Metodo per recuperare la lista delle pietanze', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_PIETANZE_NO_PAGINATE', 'getPietanzeNoPaginate', 'Metodo per recuperare la lista delle pietanze', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_DATA_ULTIMO_ACQUISTO', 'getDataUltimoAcquisto', 'Metodo per recuperare la data dell\'ultimo acquisto', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_INGREDIENTE', 'getIngrediente', 'Metodo per recuperare un ingrediente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_INGREDIENTI', 'getIngredienti', 'Metodo per recuperare la lista degli ingredienti', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_INGREDIENTI_BY_PIETANZA', 'getIngredientiByPietanza', 'Metodo per recuperare gli ingredienti di una pietanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_INGREDIENTI_DA_COMPRARE', 'getIngredientiDaComprare', 'Metodo per recuperare la lista degli ingredienti da comprare', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_LISTA_SPESA', 'getListaSpesa', 'Metodo per recuperare la lista della spesa', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_LISTA_SPESE', 'getListaSpese', 'Metodo per recuperare le liste della spesa', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_MENU_ALIMENTARE', 'getMenuAlimentare', 'Metodo per recuperare un menu alimentare', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_MENU_ALIMENTARI', 'getMenuAlimentari', 'Metodo per recuperare i menu alimentari', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_GET_COMBO_TIPO_PASTO', 'getComboTipoPasto', 'Metodo per recuperare i tipi pasto', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_ELIMINA_SPESA', 'eliminaSpesa', 'Metodo per eliminare una spesa', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_ELIMINA_PIETANZA', 'eliminaPietanza', 'Metodo per eliminare una singola pietanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_ELIMINA_INGREDIENTE', 'eliminaIngrediente', 'Metodo per eliminare un ingrediente', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_ELIMINA_MENU_ALIMENTARE', 'eliminaMenuAlimentare', 'Metodo per eliminare un menu alimentare', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_ASSOCIA_INGREDIENTE_PIETANZA', 'associaIngredientePietanza', 'Metodo per associare un ingrediente ad una pietanza', '2000-06-12 00:00:00', NULL);
INSERT INTO `au_risorse` (`idRisorsa`, `nomeMetodo`, `descrizione`, `dataCreazione`, `dataEliminazione`) VALUES('SPES_DISSOCIA_INGREDIENTE_PIETANZA', 'dissociaIngredientePietanza', 'Metodo per dissociare un ingrediente da una pietanza', '2000-06-12 00:00:00', NULL);

--
--
--
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_CHIAVE_GLOBALE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ASSOCIA_RUOLO_RISORSA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ASSOCIA_RUOLO_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ASSOCIA_RUOLO_VOCE_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_AZZERA_CONTATORE_ALERT', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_BLOCCA_INDIRIZZO_IP', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_BLOCCA_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_DISSOCIA_RUOLO_RISORSA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_DISSOCIA_RUOLO_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_DISSOCIA_RUOLO_VOCE_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ELIMINA_NOTIFICA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ELIMINA_RISORSA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ELIMINA_T_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ELIMINA_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_ELIMINA_VOCE_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_COMBO_RUOLI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_DESTINATARI_NOTIFICA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_LISTA_ACCESSI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_LISTA_DISPOSITIVI_FISICI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_LISTA_DISPOSITIVI_FISICI_TELEGRAM', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_LISTA_NOTIFICHE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_LISTA_VOCI_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_MENU_PER_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NOTIFICA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NUMERO_ACCESSI_ATTIVI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NUMERO_DISPOSITIVI_FISICI_ATTIVI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NUMERO_INDIRIZZI_IP', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NUMERO_RISORSE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NUMERO_RUOLI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NUMERO_UTENTI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_NUMERO_VOCI_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_RISORSA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_RISORSE_PER_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_STATISTICHE_METODI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_T_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_UTENTI_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_GET_VOCE_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INSERISCI_NOTIFICA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INSERISCI_RISORSA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INSERISCI_T_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INSERISCI_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INSERISCI_VOCE_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INVIA_NOTIFICA_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INVIA_NOTIFICA_TUTTI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_INVIA_NOTIFICA_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LISTA_INDIRIZZI_IP', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LISTA_RISORSE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LISTA_T_RUOLI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LISTA_UTENTI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LOG_DEBUG', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LOG_ERROR', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LOG_INFO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LOG_TELEGRAM', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_LOG_WARN', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_MODIFICA_NOTIFICA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_MODIFICA_RISORSA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_MODIFICA_T_RUOLO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_MODIFICA_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_MODIFICA_VOCE_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_NOTIFICHE_TELEGRAM', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_NUMERO_LOGIN', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_RIMUOVI_DISPOSITIVO_FISICO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_RIMUOVI_DISPOSITIVO_FISICO_TELEGRAM', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_SBLOCCA_INDIRIZZO_IP', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_SBLOCCA_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('AMM', 'AMM_TERMINA_ACCESSO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'AMM_LISTA_UTENTI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_ABILITA_TIPO_METODO_LOGIN', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_ABILITA_TIPO_RECUPERO_PASSWORD', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_DISABILITA_DISPOSITIVO_FISICO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_DISABILITA_TIPO_METODO_LOGIN', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_DISABILITA_TIPO_RECUPERO_PASSWORD', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_ELIMINA_NOTIFICA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GENERA_CODICI_BACKUP', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GENERA_CHIAVE_PERSONALE_TOTP', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GENERA_ID_DISPOSITIVO_FISICO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GENERA_ID_TELEGRAM', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_COMBO_VOCI_MENU', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_METODI_AUTENTICAZIONE_PER_UTENTE_LOGGATO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_METODI_RECUPERO_PASSWORD_UTENTE_LOGGATO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_NOTIFICA', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_NOTIFICHE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_STORICO_ACCESSI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_UTENTE_LOGGATO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_GET_VOCI_MENU_PER_UTENTE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_INVALIDA_TOKEN', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_IS_DISPOSITIVO_ABILITATO', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_LEGGI_NOTIFICHE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_LISTA_DISPOSITIVI_FISICI', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_LISTA_DISPOSITIVI_FISICI_TELEGRAM', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_VERIFICA_AUTENTICAZIONE', '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_risorse` (`idTipoRuolo`, `idRisorsa`, `dataCreazione`) VALUES('USER', 'USER_SOTTOSCRIZIONE', '2000-06-12 00:00:00');
--
--
--
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 1, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 2, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 3, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 4, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 5, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 6, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 7, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 8, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 9, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 10, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 11, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 12, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 13, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 14, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 15, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 16, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 17, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 18, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 19, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 20, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 21, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 27, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 28, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 29, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 30, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 31, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 32, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 40, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('AMM', 62, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 51, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 52, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 53, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 54, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 55, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 56, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 57, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 58, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 59, '2000-06-12 00:00:00');
INSERT INTO `au_ruoli_voci_menu` (`idTipoRuolo`, `idVoceMenu`, `dataCreazione`) VALUES('SPES', 60, '2000-06-12 00:00:00');
--
--
--
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(1, NULL, 'Gestione utenti', '#', 'fa-solid fa-user-group', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(2, NULL, 'Gestione risorse', '#', 'fa-solid fa-sitemap', 4, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(3, NULL, 'Gestione ruoli', '#', 'fa-solid fa-tags', 3, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(4, NULL, 'Gestione menu', '#', 'fa-solid fa-bars', 6, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(5, NULL, 'Visualizza Logs', '#', 'fa-solid fa-terminal', 8, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(6, NULL, 'Gestione indirizzi IP', 'pannello-di-controllo/lista-indirizzi-ip', 'fa-solid fa-location-crosshairs', 5, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(8, 1, 'Inserisci utente', 'pannello-di-controllo/scheda-utente', 'fa-solid fa-user-plus', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(9, 1, 'Lista utenti', 'pannello-di-controllo/lista-utenti', 'fa-solid fa-users', 2, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(12, 3, 'Inserisci ruolo', 'pannello-di-controllo/scheda-ruolo', 'fa-solid fa-plus', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(13, 3, 'Lista ruoli', 'pannello-di-controllo/lista-ruoli', 'fa-solid fa-list-ul', 2, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(14, 2, 'Inserisci risorsa', 'pannello-di-controllo/scheda-risorsa', 'fa-solid fa-plus', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(15, 2, 'Lista risorse', 'pannello-di-controllo/lista-risorse', 'fa-solid fa-list-ul', 2, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(16, 5, 'Livello Error', 'pannello-di-controllo/logs/error', 'fa-solid fa-xmark', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(17, 5, 'Livello Warn', 'pannello-di-controllo/logs/warn', 'fa-solid fa-triangle-exclamation', 2, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(18, 5, 'Livello Info', 'pannello-di-controllo/logs/info', 'fa-solid fa-info', 3, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(19, 5, 'Livello Debug', 'pannello-di-controllo/logs/debug', 'fa-solid fa-bug-slash', 4, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(20, 4, 'Inserisci voce di menu', 'pannello-di-controllo/scheda-voce-menu', 'fa-solid fa-plus', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(21, 4, 'Lista menu', 'pannello-di-controllo/lista-menu', 'fa-solid fa-list', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(27, NULL, 'Gestione notifiche', '#', 'fa-solid fa-bell', 7, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(28, NULL, 'Gestione dispositivi fisici', 'pannello-di-controllo/lista-dispositivi-fisici', 'fa-solid fa-mobile-screen', 6, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(29, NULL, 'Gestione accessi', 'pannello-di-controllo/lista-accessi', 'fa-solid fa-circle-nodes', 7, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(30, 27, 'Nuova notifica', 'pannello-di-controllo/scheda-notifica', 'fa-solid fa-plus', 1, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(31, 27, 'Lista notifiche', 'pannello-di-controllo/lista-notifiche', 'fa-solid fa-list', 2, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(32, NULL, 'Lista account telegram', 'pannello-di-controllo/lista-account-telegram', 'fa-brands fa-telegram', 8, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(40, NULL, 'Dashboard', 'pannello-di-controllo/dashboard', 'fa-solid fa-home', 0, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(51, NULL, 'Gestione ingredienti', '#', 'fa-solid fa-carrot', 46, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(52, 51, 'Nuovo ingrediente', 'scheda-ingrediente', 'fa-solid fa-plus', 47, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(53, 51, 'Lista ingredienti', 'lista-ingredienti', 'fa-solid fa-list', 48, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(54, NULL, 'Gestione pietanze', '#', 'fa-solid fa-hotdog', 49, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(55, 54, 'Nuova pietanza', 'scheda-pietanza', 'fa-solid fa-plus', 50, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(56, 54, 'Lista pietanze', 'lista-pietanze', 'fa-solid fa-list', 51, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(57, NULL, 'Gestione spesa', '#', 'fa-solid fa-cart-shopping', 52, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(58, 57, 'Nuova spesa', 'scheda-spesa', 'fa-solid fa-plus', 52, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(59, 57, 'Lista spese', 'lista-spese', 'fa-solid fa-list', 53, 1, '2000-06-12 00:00:00', NULL);
INSERT INTO `au_voci_menu` (`idVoceMenu`, `idVoceMenuPadre`, `descrizione`, `path`, `icona`, `ordine`, `visibile`, `dataCreazione`, `dataEliminazione`) VALUES(60, NULL, 'Gestione menu alimentare', 'menu-alimentare', 'fa-solid fa-calendar-days', 53, 1, '2000-06-12 00:00:00', NULL);
---
---
---
INSERT INTO `au_t_pasti` (`idTipoPasto`, `nome`, `ordine`) VALUES('CENA', 'Cena', 5);
INSERT INTO `au_t_pasti` (`idTipoPasto`, `nome`, `ordine`) VALUES('COLAZIONE', 'Colazione', 1);
INSERT INTO `au_t_pasti` (`idTipoPasto`, `nome`, `ordine`) VALUES('PRANZO', 'Pranzo', 3);
INSERT INTO `au_t_pasti` (`idTipoPasto`, `nome`, `ordine`) VALUES('SPUNTINO_MATTINA', 'Spuntino mattutino', 2);
INSERT INTO `au_t_pasti` (`idTipoPasto`, `nome`, `ordine`) VALUES('SPUNTINO_POMERIDIANO', 'Spuntino pomeridiano', 4);
